= Lab 2 - Introspection, Monitoring, and Metrics using Spring Boot Actuator

_A completed version of this lab is found at `$COURSE_HOME/labs/complete/hello-spring-boot`._

== Set up the Actuator

. Continue with the project you completed in link:lab_01.html[Lab 1].

. To `pom.xml` add the following dependency to include the starter for Spring Boot Actuator:
+
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----

. To the main YAML document in `application.yml` add the following:
+
----
management:
  endpoints:
    web:
      exposure:
        include: "*"
----
+
"*" can be used to select all endpoints. For example, to expose everything over HTTP.

== Introspection Endpoints

. Build the application:
+
----
$ ./mvnw package
----

. Run the application:
+
----
$ java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar
----

. Try out the following endpoints. The output is omitted here because it can be quite large:
+
http://localhost:8080/actuator/beans:: Dumps all of the beans in the Spring context.
http://localhost:8080/actuator/conditions:: Shows the conditions that were evaluated on configuration and auto-configuration classes and the reasons why they did or did not match.
http://localhost:8080/actuator/configprops:: Displays a collated list of all `@ConfigurationProperties`.
http://localhost:8080/actuator/env:: Dumps the application's shell environment as well as all Java system properties.
http://localhost:8080/actuator/mappings:: Dumps all URI request mappings and the controller methods to which they are mapped.
http://localhost:8080/actuator/dump:: Performs a thread dump.
http://localhost:8080/actuator/trace:: Displays trace information (by default the last few HTTP requests).

. Stop the application (e.g. via CTRL-C).

== Build and Version Control Info

Spring Boot provides an endpoint (http://localhost:8080/actuator/info) that allows the exposure of arbitrary metadata.

One thing that it does well is expose information about the specific build and version control coordinates for a given deployment.

. Add the following plugin to your Maven build.
It will add Git branch and commit coordinates to the `/info` endpoint:
+
----
<plugin>
	<groupId>pl.project13.maven</groupId>
	<artifactId>git-commit-id-plugin</artifactId>
	<configuration>
		<dotGitDirectory>../../../.git</dotGitDirectory>
	</configuration>
</plugin>
----
+
NOTE: The path `../../../.git` refers to the `.git` directory at the root of the course materials.

. Add the following properties to `src/main/resources/application.yml`:
+
----
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
----
+
These properties should be added to the topmost YAML document, above the `---`. They will add the project's Maven coordinates to the `/info` endpoint. The Spring Boot Maven plugin will cause them to automatically be replaced in the assembled JAR.

. Build the application:
+
----
$ ./mvnw package
----

. Run the application:
+
----
$ java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar
----

. Visit the application in the browser (http://localhost:8080/actuator/info), and verify that the output is similar to the following:
+
----
{
   "git" : {
      "commit" : {
         "time" : "2015-12-06T17:25:32-0500",
         "id" : "78b0e1b"
      },
      "branch" : "master"
   },
   "build" : {
      "version" : "0.0.1-SNAPSHOT",
      "name" : "hello-spring-boot",
      "artifact" : "hello-spring-boot",
      "description" : "Demo project for Spring Boot"
   }
}
----

. Stop the application (e.g. via CTRL-C).

== Health Indicators

Spring Boot provides an endpoint (http://localhost:8080/actuator/health) that allows for the notion of various health indicators.

. Create the class `io.pivotal.spring.hellospringboot.FlappingHealthIndicator` and into it paste the following code:
+
----
@Component
public class FlappingHealthIndicator implements HealthIndicator{

    private Random random = new Random(System.currentTimeMillis());

    @Override
    public Health health() {
        int result = random.nextInt(100);
        if (result < 50) {
            return Health.down().withDetail("flapper", "failure").withDetail("random", result).build();
        } else {
            return Health.up().withDetail("flapper", "ok").withDetail("random", result).build();
        }
    }
}
----
+
This demo health indicator will randomize the health check.

. In order to see all details from the health endpoint add the following to your application.yml:
+
----
management:
  endpoint:
    health:
      show-details: always
----
+
. Build the application:
+
----
$ ./mvnw package
----

. Run the application:
+
----
$ java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar
----

. Visit the application in the browser (http://localhost:8080/actuator/health), and verify that the output is similar to the following (and changes randomly!):
+
----
{
  "status": "DOWN",
  "details": {
    "flapping": {
      "status": "DOWN",
      "details": {
        "flapper": "failure",
        "random": 7
      }
    },
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": 499963174912,
        "free": 220829589504,
        "threshold": 10485760
      }
    }
  }
}
----

. Stop the application (e.g. via CTRL-C).

== Metrics

Spring Boot provides an endpoint (http://localhost:8080/actuator/metrics) that exposes several automatically collected metrics for your application.
It also allows for the creation of custom metrics.

. Create the class `io.pivotal.spring.hellospringboot.GreetingService` and into it paste the following code:
+
----
@Component
public class GreetingService {

    @Value("${greeting}")
    String greeting;

    private final Counter counter;

	public GreetingService(MeterRegistry registry) {
		this.counter = registry.counter("my.counter");
	}

    public String getGreeting() {
		this.counter.increment();
        return greeting;
    }
}
----
+
This class injects the MeterRegistry in your component and registers a counter metric.

. Refactor the contents of the class `io.pivotal.spring.hellospringboot.HelloSpringBootApplication`:
+
----
@Value("${greeting}")
String greeting;

@Autowired
private GreetingService greetingService;

@RequestMapping("/")
public String hello() {
		return String.format("%s World!", greetingService.getGreeting());
}

public static void main(String[] args) {
	SpringApplication.run(HelloSpringBootApplication.class, args);
}
----
+
`hello()` is now delegating the source of the greeting to our newly created `GreetingService`.

. Build the application:
+
----
$ ./mvnw package
----

. Run the application:
+
----
$ java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar
----

. Visit the application in the browser (http://localhost:8080) and refresh the page several times.

. Now visit the `/metrics` endpoint (http://localhost:8080/actuator/metrics).
Among the autogenerated metrics you should see `my.counter` for the `GreetingService` invocations.

. Now visit http://localhost:8080/actuator/metrics/my.counter to see the current value
+
----
{
  "name": "my.counter",
  "description": null,
  "baseUnit": null,
  "measurements": [
    {
      "statistic": "COUNT",
      "value": 4.0
    }
  ],
  "availableTags": [

  ]
}
----

. Stop the application (e.g. via CTRL-C).

. To learn more about the metrics, visit http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html.
